### ISSUE TITLE
[PyPy, Jython]: Solver function "miscomputes".

### ISSUE THREAD

**Issue by oskar-skog** [oskar-skog/anonymine#5]
The PyPy implementation of Python refuses to run the solver algo as expected and seems to
cause cells to be double solved.

    Traceback (archived version 0.0.29):
        Traceback (most recent call last):
            File "<stdin>", line 1, in <module>
            File "test.py", line 258, in runneumann
                print(solver.solve())
            File "anonymine_solver.py", line 1115, in solve
                success, update_difficulty = self.solver_loop()
            File "anonymine_solver.py", line 978, in solver_loop
                status = self.cell_solver(cell, 4*i + j)
            File "anonymine_solver.py", line 842, in cell_solver
                """.format(possibilities)
        AssertionError: 
            Cell already solved?? []

**Comment by oskar-skog** [comment]
The `number_neighbours` method does not always return the same.

There's a `pypybug` function in test.py and a commented out `print` in `number_neighbours`.

**Comment by oskar-skog** [comment]
Looks like it's either my fault, or Jython has reused some PyPy code.
Jython 2.7 behaves the same way.

**Comment by oskar-skog** [comment]
-                if self.field.get(neighbour) is 'F':
    +                if neighbour_value == 'F':      # The bug was here!!!!!!!11
